"""remove location

Revision ID: 1d26fe0f6dfa
Revises: d4abd6b3fe91
Create Date: 2025-01-02 00:20:42.458801

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d26fe0f6dfa'
down_revision: Union[str, None] = 'd4abd6b3fe91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
