"""connect member to gym

Revision ID: 8ecdc075a962
Revises: 1d26fe0f6dfa
Create Date: 2025-01-02 15:37:04.837973

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecdc075a962'
down_revision: Union[str, None] = '1d26fe0f6dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyms', sa.Column('member_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'gyms', 'members', ['member_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gyms', type_='foreignkey')
    op.drop_column('gyms', 'member_uid')
    # ### end Alembic commands ###
